<a href="https://colab.research.google.com/github/NishaimLimbu/classes/blob/main/movie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [45]:
data=pd.read_csv("movie.csv")
data.head()

Title  Year  Director  Duration  Rating   Votes  \
0  Winds of Fate 4  1980    R. Lee       167     4.1  182425   
1     Firestorm 11  2014   S. Chen       166     4.1  449351   
2    Silent Echo 2  2016   A. Khan       170     4.1  363328   
3    City Lights 4  1982  L. Zhang       170     9.9   62371   
4   Broken Truth 1  1990  L. Zhang        91     5.3    4600   

                                         Description  Language Country  \
0   A touching love story with heartwarming moments.   Spanish   China   
1  A fast-paced thriller with intense action scenes.    Korean   China   
2  A fast-paced thriller with intense action scenes.    Korean   Japan   
3  An emotional journey exploring complex charact...  Japanese   Japan   
4  An imaginative world filled with magic and won...    Korean     USA   

   Budget_USD  BoxOffice_USD    Genre Production_Company Content_Rating  \
0    39979615      179936008  Romance         DreamWorks              R   
1   116404774      802121619   Action            Netflix              R   
2   166261330      225526871   Action              Pixar             PG   
3    28861315       69813738    Drama            Netflix          NC-17   
4    43890403      375136716  Fantasy      Studio Ghibli             PG   

         Lead_Actor  Num_Awards  Critic_Reviews  
0    Kangana Ranaut           8             229  
1    Kangana Ranaut          20             466  
2  Amitabh Bachchan          16             539  
3   Natalie Portman          15             606  
4       Chris Evans           6             330

In [46]:
data.shape


(50000, 17)

In [47]:
data.columns

Index(['Title', 'Year', 'Director', 'Duration', 'Rating', 'Votes',
       'Description', 'Language', 'Country', 'Budget_USD', 'BoxOffice_USD',
       'Genre', 'Production_Company', 'Content_Rating', 'Lead_Actor',
       'Num_Awards', 'Critic_Reviews'],
      dtype='object')

In [48]:
data.isnull().sum()

Title                 0
Year                  0
Director              0
Duration              0
Rating                0
Votes                 0
Description           0
Language              0
Country               0
Budget_USD            0
BoxOffice_USD         0
Genre                 0
Production_Company    0
Content_Rating        0
Lead_Actor            0
Num_Awards            0
Critic_Reviews        0
dtype: int64

In [49]:
data.describe()

Year     Duration        Rating          Votes    Budget_USD  \
count  50000.000000  50000.00000  50000.000000   50000.000000  5.000000e+04   
mean    2001.562620    130.07312      6.926472  249699.050540  9.179143e+07   
std       12.722539     29.11097      1.698758  144314.043032  5.823888e+07   
min     1980.000000     80.00000      4.000000     516.000000  1.135566e+06   
25%     1991.000000    105.00000      5.500000  124531.500000  4.389040e+07   
50%     2002.000000    130.00000      6.900000  248582.000000  8.062480e+07   
75%     2013.000000    155.00000      8.400000  374833.500000  1.475557e+08   
max     2023.000000    180.00000      9.900000  499984.000000  1.984445e+08   

       BoxOffice_USD    Num_Awards  Critic_Reviews  
count   5.000000e+04  50000.000000    50000.000000  
mean    5.176063e+08      9.964440      500.176380  
std     2.880283e+08      6.066303      289.971792  
min     3.291117e+06      0.000000        0.000000  
25%     2.590329e+08      5.000000      248.000000  
50%     5.109973e+08     10.000000      500.000000  
75%     7.704129e+08     15.000000      751.000000  
max     9.925159e+08     20.000000     1000.000000

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Title               50000 non-null  object 
 1   Year                50000 non-null  int64  
 2   Director            50000 non-null  object 
 3   Duration            50000 non-null  int64  
 4   Rating              50000 non-null  float64
 5   Votes               50000 non-null  int64  
 6   Description         50000 non-null  object 
 7   Language            50000 non-null  object 
 8   Country             50000 non-null  object 
 9   Budget_USD          50000 non-null  int64  
 10  BoxOffice_USD       50000 non-null  int64  
 11  Genre               50000 non-null  object 
 12  Production_Company  50000 non-null  object 
 13  Content_Rating      50000 non-null  object 
 14  Lead_Actor          50000 non-null  object 
 15  Num_Awards          50000 non-null  int64  
 16  Crit

In [51]:
data.sample(6)

Title  Year    Director  Duration  Rating   Votes  \
12735      Firestorm 1  1982    M. Brown       148     4.8  300419   
45449  Midnight Sun 14  2023    D. Patel       179     5.6  387522   
46598   Quiet Heart 18  1995  T. Johnson       112     9.0  166147   
25428    Lost World 12  2014    L. Zhang        85     4.2  262761   
32507    Silent Echo 8  2012  T. Johnson       146     4.9  266504   
31789  Last Mission 10  1991    J. Smith       178     7.6  438346   

                                             Description  Language  \
12735   A light-hearted comedy that guarantees laughter.   English   
45449   A light-hearted comedy that guarantees laughter.  Mandarin   
46598  A fast-paced thriller with intense action scenes.    Korean   
25428  An imaginative world filled with magic and won...     Hindi   
32507  An imaginative world filled with magic and won...  Japanese   
31789  A suspenseful plot filled with unexpected twists.    French   

           Country  Budget_USD  BoxOffice_USD     Genre  Production_Company  \
12735  South Korea   144253410      524169054    Comedy       Studio Ghibli   
45449  South Korea    39979615      821037985    Comedy         Warner Bros   
46598        India    34107905      561084152    Action          DreamWorks   
25428        India   150236893      524683816   Fantasy       Studio Ghibli   
32507        China   158652694      400204169   Fantasy  Paramount Pictures   
31789  South Korea    43890403      441616339  Thriller          DreamWorks   

      Content_Rating        Lead_Actor  Num_Awards  Critic_Reviews  
12735              R  Amitabh Bachchan           3             102  
45449          NC-17     Anne Hathaway          16             439  
46598             PG   Natalie Portman          20             367  
25428          NC-17       Emma Watson           4             521  
32507          NC-17         Tom Hanks           7             283  
31789              G       Emma Watson          10             965

In [52]:
# Drop columns that do not contribute directly to classification
data = data.drop(['Language', 'Country', 'Content_Rating','Director', 'Production_Company', 'Lead_Actor'], axis=1)

In [53]:
# Encode categorical variables
categorical_cols = ['Title', 'Description' ] #, 'Language', 'Country', 'Content_Rating'
le = LabelEncoder()
for col in categorical_cols:
    data[col] = le.fit_transform(data[col])

# Encode target variable
data['Genre'] = le.fit_transform(data['Genre'])

In [54]:
# Separate features and target
X = data[['Title', 'Description', 'Budget_USD']]
y = data['Genre']

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [56]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [57]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:\n', cm)

# Classification Report
print('Classification Report:\n', classification_report(y_test, y_pred))

Accuracy: 1.0
Confusion Matrix:
 [[2114    0    0    0    0    0    0]
 [   0 2161    0    0    0    0    0]
 [   0    0 2154    0    0    0    0]
 [   0    0    0 2116    0    0    0]
 [   0    0    0    0 2188    0    0]
 [   0    0    0    0    0 2152    0]
 [   0    0    0    0    0    0 2115]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2114
           1       1.00      1.00      1.00      2161
           2       1.00      1.00      1.00      2154
           3       1.00      1.00      1.00      2116
           4       1.00      1.00      1.00      2188
           5       1.00      1.00      1.00      2152
           6       1.00      1.00      1.00      2115

    accuracy                           1.00     15000
   macro avg       1.00      1.00      1.00     15000
weighted avg       1.00      1.00      1.00     15000



In [58]:
# Create individual models
model1 = LogisticRegression(max_iter=200)
model2 = DecisionTreeClassifier()
model3 = RandomForestClassifier()

# Create Voting Classifier
voting_model = VotingClassifier(estimators=[('lr', model1), ('dt', model2), ('rf', model3)], voting='hard')

# Train the ensemble model
voting_model.fit(X_train, y_train)

# Evaluate the ensemble model
y_pred_voting = voting_model.predict(X_test)
voting_accuracy = accuracy_score(y_test, y_pred_voting)
print('Voting Classifier Accuracy:', voting_accuracy)

# Classification Report for Ensemble
print('Classification Report:\n', classification_report(y_test, y_pred_voting))

Voting Classifier Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2114
           1       1.00      1.00      1.00      2161
           2       1.00      1.00      1.00      2154
           3       1.00      1.00      1.00      2116
           4       1.00      1.00      1.00      2188
           5       1.00      1.00      1.00      2152
           6       1.00      1.00      1.00      2115

    accuracy                           1.00     15000
   macro avg       1.00      1.00      1.00     15000
weighted avg       1.00      1.00      1.00     15000

