<a href="https://colab.research.google.com/github/NishaimLimbu/classes/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [2]:
#Tensors type:
# zero dim tensor: Scalar
#1d tensor: Vector
#2d tensor: Martix
#3d tensor: Tensor


In [3]:
scalar=tf.constant(5)
vector = tf.constant([1,3,2])
matrix = tf.constant([[1,3,2],[2,3,1]])
tensor = tf.constant([[[1,2,3],[3,3,2],[2,1,3]]])

In [4]:
print (vector)
print (matrix)
print (tensor)

tf.Tensor([1 3 2], shape=(3,), dtype=int32)
tf.Tensor(
[[1 3 2]
 [2 3 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [3 3 2]
  [2 1 3]]], shape=(1, 3, 3), dtype=int32)


In [5]:
a=tf.constant([3,2])
b=tf.constant([5,34])
print (tf.add(a,b))

tf.Tensor([ 8 36], shape=(2,), dtype=int32)


In [6]:
a=tf.constant([33,24])
b=tf.constant([52,34])
print (tf.subtract(a,b))

tf.Tensor([-19 -10], shape=(2,), dtype=int32)


In [7]:
a=tf.constant([32,21])
b=tf.constant([53,34])
print (tf.multiply(a,b))

tf.Tensor([1696  714], shape=(2,), dtype=int32)


In [8]:
a=tf.constant([32,21])
b=tf.constant([53,34])
print (tf.divide(a,b))

tf.Tensor([0.60377358 0.61764706], shape=(2,), dtype=float64)


In [9]:
a=tf.constant([[32,21],[34,23]])
b=tf.constant([[53,32],[23,43]])
print (tf.matmul(a,b))
print (tf.transpose(b))

tf.Tensor(
[[2179 1927]
 [2331 2077]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[53 23]
 [32 43]], shape=(2, 2), dtype=int32)


In [10]:
data=tf.constant([[1,3],[3,2]])
print (tf.reduce_sum(data))
print (tf.reduce_min(data))
print (tf.reduce_max(data))
print (tf.reduce_mean(data))

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [11]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense


In [12]:
#1st way to define model
model = Sequential([
    Dense(64, activation='relu', input_shape=(50,)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(3, activation='softmax')
])

# 2 way to define a model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(50,))),
model.add(Dense(32, activation='relu')),
model.add(Dense(16, activation='relu')),
model.add(Dense(3, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
#functional API
from tensorflow.keras import Input,Model
from tensorflow.keras.layers import Dense, Concatenate

# Define input layer
inputs = Input(shape=(784,))

# Build layers
x= Dense (64, activation='relu')(inputs)
x=Dense (32,activation='relu')(x)
x=Dense (16,activation='relu')(x)
outputs=Dense(3, activation='softmax')(x)

#Initialize the model
model = model(inputs, outputs=outputs)

TypeError: got an unexpected keyword argument 'outputs'

In [15]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [16]:
iris=load_iris()

In [17]:
x=iris.data
y=iris.target

In [18]:
y=to_categorical(y)

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=43)

In [20]:
model=Sequential()

In [21]:
#add first layer with no of inputs
model.add(Dense(10,input_dim=4,activation='relu'))

In [22]:
#Output layer
model.add(Dense(3,activation='softmax'))

In [23]:
#compile the model
model.compile(optimizer='adam', loss="categorical_crossentropy", metrics=['accuracy'])

In [24]:
#Train the model
model.fit(x_train,y_train, epochs=50, verbose=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.3202 - loss: 5.8348
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3442 - loss: 5.3787 
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3285 - loss: 5.3088
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3577 - loss: 4.8382
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3744 - loss: 4.5122 
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3306 - loss: 4.5871 
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3660 - loss: 4.1639
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3660 - loss: 3.9726
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3369 - loss: 3.9749 
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3462 - loss: 3.7192
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3535 - loss: 3.4604
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2973 - loss: 3.5768 


In [25]:
loss, accuracy =model.evaluate(x_test,y_test)
print (f"test accuracy {accuracy}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step - accuracy: 0.7333 - loss: 0.7272
test accuracy 0.7333333492279053


In [26]:
#how to add 4 hidden layers
model.add(Dense(128, input_dim=4, activation='relu'))


In [27]:
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(3,activation='softmax'))

In [28]:
model.compile(optimizer='adam',loss='categorical_crossentropy', metrics=['accuracy'])


In [31]:
model.fit(x_train,y_train, epochs=50, verbose=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9650 - loss: 0.1048 
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9321 - loss: 0.1373 
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9510 - loss: 0.0958 
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 0.9858 - loss: 0.0573 
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9765 - loss: 0.0835
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9806 - loss: 0.0742
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9437 - loss: 0.1080 
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9733 - loss: 0.0723 
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9806 - loss: 0.0668
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9394 - loss: 0.1095
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9658 - loss: 0.0755
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9733 - loss: 0.

In [32]:
loss, accuracy =model.evaluate(x_test,y_test)
print (f"test accuracy {accuracy}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9667 - loss: 0.0495
test accuracy 0.9666666388511658
